[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault_2024 = "73kVpBT3u7awKf4N7aW3QqUbbDgb6PKvHN7SgD7YwSXf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/akshatsharma/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
